print("Calculator")
num_1, num_2 = input("Enter two values").split(",")
print(int(num_1)+int(num_2))
print(int(num_1)*int(num_2))
print(int(num_1)//int(num_2))
print(int(num_1)/int(num_2))
print(int(num_1)-int(num_2))
print(int(num_1)**int(num_2))
